const PRODUCT_DATA = [
  {
    id: 1,
    brand: 'adidas',
    cat: 'running',
    name: 'adidas Ultraboost Web DNA',
    price: 190.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dna-neon.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dna-neon-small.webp',
  },
  {
    id: 2,
    brand: 'adidas',
    cat: 'running',
    name: 'adidas Ultraboost Web DNA (Blue)',
    price: 180.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dna.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dna-small.webp',
  },
  {
    id: 3,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas Crazy 97',
    price: 130.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-crazy.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-crazy-smallwebp.webp',
  },
  {
    id: 4,
    brand: 'adidas',
    cat: 'basketball',
    name: 'adidas D.O.N. Issue 3',
    price: 120.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-d.o.n-v3.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-d.o.n-v3-small.webp',
  },
  {
    id: 5,
    brand: 'adidas',
    cat: 'basketball',
    name: 'adidas Dame 8',
    price: 120.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dame-8-yellow-purple.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dame-8-yellow-purple-small.webp',
  },
  {
    id: 6,
    brand: 'adidas',
    cat: 'basketball',
    name: 'adidas Dame 8 Certified',
    price: 130.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dame-8.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-dame-8-small.webp',
  },
  {
    id: 7,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas NMD R1',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-originals-black-blue.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-originals-black-blue-small.webp',
  },
  {
    id: 8,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas NMD R1 (White/Blue/Red)',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-originals.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-originals-small.webp',
  },
  {
    id: 8,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas Superstar (White/Red)',
    price: 69.99,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-superstart.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-superstart-small.webp',
  },
  {
    id: 9,
    brand: 'adidas',
    cat: 'basketball',
    name: 'adidas Trae Young 2.0',
    price: 140,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-trae-young-2.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-trae-young-2-small.webp',
  },
  {
    id: 10,
    brand: 'adidas',
    cat: 'running',
    name: 'adidas Ultraboost 22',
    price: 130,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-22.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-22-small.webp',
  },
  {
    id: 11,
    brand: 'adidas',
    cat: 'running',
    name: 'adidas Ultraboost 22 Mesh',
    price: 120,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-multi.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-multi-small.webp',
  },
  {
    id: 12,
    brand: 'adidas',
    cat: 'running',
    name: 'adidas Ultraboost DNA (Red/Black)',
    price: 160,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-red-black.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-red-black-small.webp',
  },
  {
    id: 13,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas Ultraboost 5.0 DNA (Blue/Yellow)',
    price: 140,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-running.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultra-running-small.webp',
  },
  {
    id: 13,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas Ultraboost 5.0 Breakfast',
    price: 150,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultraboost-breakfast.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultraboost-breakfast-small.webp',
  },
  {
    id: 13,
    brand: 'adidas',
    cat: 'lifestyle',
    name: 'adidas Ultraboost DNA (White)',
    price: 150,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultraboost-white.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/adidas/adidas-ultraboost-white-small.webp',
  },
  {
    id: 14,
    brand: 'puma',
    cat: 'basketball',
    name: 'PUMA Go',
    price: 70,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-b&w.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-b&w-small.webp',
  },
  {
    id: 14,
    brand: 'puma',
    cat: 'basketball',
    name: 'PUMA Nitro',
    price: 70,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-colorful-alt.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-colorful-alt-small.webp',
  },
  {
    id: 15,
    brand: 'puma',
    cat: 'basketball',
    name: 'PUMA MB.02 Rick & Morty',
    price: 140,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-colorful.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-colorful-small.webp',
  },
  {
    id: 16,
    brand: 'puma',
    cat: 'basketball',
    name: 'PUMA MB.02 (Black)',
    price: 99.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-mb2-black.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-mb2-black-small.webp',
  },
  {
    id: 17,
    brand: 'puma',
    cat: 'basketball',
    name: 'PUMA MB.02 (Blue)',
    price: 99.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-mb2-blue.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-mb2-blue-small.webp',
  },
  {
    id: 18,
    brand: 'puma',
    cat: 'basketball',
    name: 'PUMA MB.02 (Light Blue)',
    price: 99.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-mb2-lightblue.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/puma/puma-mb2-lightblue-small.webp',
  },
  {
    id: 19,
    brand: 'puma',
    cat: 'lifestyle',
    name: 'PUMA Slipstream',
    price: 90.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-orange.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-orange-small.webp',
  },
  {
    id: 20,
    brand: 'puma',
    cat: 'lifestyle',
    name: 'PUMA Slipstream (Black/Red)',
    price: 100.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-red-and-black.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/puma/puma-red-and-black-small.webp',
  },
  {
    id: 21,
    brand: 'puma',
    cat: 'lifestyle',
    name: 'PUMA Slipstream (White/Red)',
    price: 100.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-slipstream.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-slipstream-small.webp',
  },
  {
    id: 21,
    brand: 'puma',
    cat: 'lifestyle',
    name: 'PUMA Spongebob',
    price: 100.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-yellow.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/puma/puma-yellow-small.webp.webp',
  },
  {
    id: 22,
    brand: 'nike',
    cat: 'basketball',
    name: 'Nike Zoom GT Cut',
    price: 170.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-zoom.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-zoom-small.webp',
  },
  {
    id: 23,
    brand: 'nike',
    cat: 'basketball',
    name: 'Nike Air Max Plus 3',
    price: 195.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-airmax-blue.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-airmax-blue-small.webp',
  },
  {
    id: 24,
    brand: 'nike',
    cat: 'basketball',
    name: 'Nike Air Max Plus 3 COA',
    price: 195.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-airmax-colorful.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-airmax-colorful-small.webp',
  },
  {
    id: 24,
    brand: 'nike',
    cat: 'basketball',
    name: 'Nike Air Zoom',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-airzoom.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-airzoom-small.webp',
  },
  {
    id: 25,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Cosmic Unity 2',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cosmic-black.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cosmic-black-small.webp',
  },
  {
    id: 26,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Cosmic Unity 2 (Multi/Grey/Blue)',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cosmic.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cosmic-small.webp',
  },
  {
    id: 27,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Zoom Flight 95',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flight.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flight-small.webp',
  },
  {
    id: 28,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air VaporMax 2021 Flyknit',
    price: 200.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flyknit-blue.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flyknit-blue-small.webp',
  },
  {
    id: 29,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air VaporMax 2021 Flyknit (Leopard)',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flyknit-leapord.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flyknit-leapord-small.webp',
  },
  {
    id: 30,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air VaporMax 2021 Flyknit (Leopard)',
    price: 160.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flyknit-leapord.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-flyknit-leapord-small.webp',
  },
  {
    id: 31,
    brand: 'nike',
    cat: 'basketball',
    name: 'Nike Kyrie Infinity',
    price: 95.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-kyrie-infinity.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-kyrie-infinity-small.webp',
  },
  {
    id: 32,
    brand: 'nike',
    cat: 'running',
    name: 'Nike React Infinity Tun FK 3',
    price: 160,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-react.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-react-small.webp',
  },
  {
    id: 33,
    brand: 'nike',
    cat: 'running',
    name: 'Nike Tempo Next',
    price: 200,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-tempo.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-tempo-small.webp',
  },
  {
    id: 34,
    brand: 'nike',
    cat: 'lifestyle',
    name: "Nike Air Uptempo '96",
    price: 170,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-uptempo.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-uptempo-small.webp',
  },
  {
    id: 35,
    brand: 'nike',
    cat: 'lifestyle',
    name: "Nike Air Uptempo '96",
    price: 170,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-uptempo.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-uptempo-small.webp',
  },
  {
    id: 36,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air Vapormax',
    price: 180,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-black.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-black-small.webp',
  },
  {
    id: 37,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air Vapormax (Red)',
    price: 199.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-red.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-red-small.webp',
  },
  {
    id: 37,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air Vapormax Plus',
    price: 199.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-white.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-white-small.webp',
  },
  {
    id: 38,
    brand: 'nike',
    cat: 'lifestyle',
    name: 'Nike Air Vapormax Plus',
    price: 199.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-white.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-vapormax-white-small.webp',
  },
  {
    id: 39,
    brand: 'nike',
    cat: 'slides',
    name: 'Nike Air Max Cirro Slide',
    price: 55.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cirro-slides-black.webp',
    thumb:
      'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cirro-slides-black-small.webp',
  },
  {
    id: 40,
    brand: 'nike',
    cat: 'slides',
    name: 'Nike Air Max Cirro Slide (Black/Red)',
    price: 55.0,
    size: [
      '6',
      '6.5',
      '7',
      '7.5',
      '8',
      '8.5',
      '9',
      '9.5',
      '10',
      '10.5',
      '11',
      '11.5',
      '12',
      '12.5',
      '13',
      '14',
      '15',
    ],
    url: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cirro-slides.webp',
    thumb: 'gs://yeetfleet-2c8fa.appspot.com/nike/nike-cirro-slides-small.webp',
  },
];
